# My Jupyter Notebook on IBM Watson Studio

**Castelnau Alexandre**

*Engineering student who want to know how to handle data*

### Code giving the k-first line of Pascal's triangle

In [7]:
import numpy as np

def pascal(k):
    pasTri = np.zeros((k,k))
    pasTri[0, 0]=1
    
    i, j = 1, 0
    
    while i<k:
        while j<=i:
            pasTri[i, j] = pasTri[i-1, j] + pasTri[i-1, j-1]
            j+=1
        j=0
        i+=1
    
    return pasTri
        
print(pascal(10))

[[  1.   0.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   1.   0.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   2.   1.   0.   0.   0.   0.   0.   0.   0.]
 [  1.   3.   3.   1.   0.   0.   0.   0.   0.   0.]
 [  1.   4.   6.   4.   1.   0.   0.   0.   0.   0.]
 [  1.   5.  10.  10.   5.   1.   0.   0.   0.   0.]
 [  1.   6.  15.  20.  15.   6.   1.   0.   0.   0.]
 [  1.   7.  21.  35.  35.  21.   7.   1.   0.   0.]
 [  1.   8.  28.  56.  70.  56.  28.   8.   1.   0.]
 [  1.   9.  36.  84. 126. 126.  84.  36.   9.   1.]]


Hope you enjoy to remember how to have the binomial coefficients $\binom{k}{i}$ in the famous formula : $$(a+b)^k = \sum_{i=0}^k \binom{k}{i} a^{i} b^{k-i} $$
Remember that binomial coefficients can be compute by different methods : 
* Pascal's Triangle
* Factorial formula

Please found more on binomial theorem and coefficient :
1. [Wikipedia][1]
2. [Je retiens][2]

[1]: https://fr.wikipedia.org/wiki/Formule_du_bin%C3%B4me_de_Newton
[2]: https://jeretiens.net/le-coefficient-binomial/